### ISSUE TITLE
TODO: Hakchi THE Randomizer

### ISSUE THREAD

**Issue by DefKorns** [DefKorns/Hakchi_Theme_Randomizer#3]
### TODO: Hakchi THE Randomizer

- [ ] Add Shonen Jump support
- [ ] Subfolder matching parent
- [ ] When file not fount mount original files
- [ ] Custom NES themes
- [ ] Fix Boot Randomizer

**Comment by DefKorns** [comment]
# Added Shonen Jump support.

### now theme folders are:
- shonen
- nes
- snes

**Comment by DefKorns** [comment]
# Fix: overmounting

### when new theme don't contain all the required files overmount the default ones

**Comment by DefKorns** [comment]
# Custom font support

- fixed chmenu wait with CE v3.5.0 file
- Added support to copyright, s, m, l font
- minor fixes
